const quotes: Record<string, string[]> = {
	english: [
		"The only limit to our realization of tomorrow is our doubts of today.",
		"In the middle of every difficulty lies opportunity.",
		"It does not matter how slowly you go as long as you do not stop.",
		"Success usually comes to those who are too busy to be looking for it.",
		"Do not watch the clock do what it does keep going.",
		"Life is what happens when you are busy making other plans.",
		"If you tell the truth you do not have to remember anything.",
		"Believe you can and you are halfway there.",
		"The future depends on what you do today.",
		"Happiness is not something ready made it comes from your own actions.",
		"Do what you can with what you have where you are.",
		"Failure is simply the opportunity to begin again this time more intelligently.",
		"The best time to plant a tree was twenty years ago the second best time is now.",
		"An unexamined life is not worth living.",
		"Spread love everywhere you go let no one ever come to you without leaving happier.",
	],
	russian: [
		"Единственный способ делать великую работу это любить то что делаешь.",
		"В середине каждой трудности скрывается возможность.",
		"Не важно как медленно ты идёшь главное не останавливаться.",
		"Будущее зависит от того что ты делаешь сегодня.",
		"Жизнь это то что происходит пока ты строишь другие планы.",
		"Верь что ты можешь и ты уже на полпути.",
		"Счастье это не готовый продукт оно исходит из твоих собственных действий.",
		"Делай что можешь с тем что имеешь там где ты есть.",
		"Неудача это просто возможность начать снова но более умно.",
		"Лучшее время посадить дерево было двадцать лет назад второе лучшее время сейчас.",
		"Тот кто хочет видит возможности тот кто не хочет видит препятствия.",
		"Успех это не конечная точка провал не фатален важно лишь мужество продолжать.",
		"Мы сами являемся хозяевами своей судьбы.",
		"Человек который никогда не ошибался никогда не пробовал ничего нового.",
		"Стремись не к успеху а к ценностям которые он даёт.",
	],
	spanish: [
		"La única forma de hacer un gran trabajo es amar lo que haces.",
		"En medio de cada dificultad yace una oportunidad.",
		"No importa lo lento que vayas siempre y cuando no te detengas.",
		"El futuro depende de lo que hagas hoy.",
		"La vida es lo que pasa mientras estás ocupado haciendo otros planes.",
		"Cree que puedes y ya estás a mitad del camino.",
		"La felicidad no es algo ya hecho viene de tus propias acciones.",
		"Haz lo que puedas con lo que tienes donde estás.",
		"El fracaso es simplemente la oportunidad de comenzar de nuevo esta vez más inteligentemente.",
		"El mejor momento para plantar un árbol fue hace veinte años el segundo mejor momento es ahora.",
		"El éxito no es definitivo el fracaso no es fatal lo que cuenta es el valor de continuar.",
		"La creatividad es la inteligencia divirtiéndose.",
		"No cuentes los días haz que los días cuenten.",
		"Primero resuelve el problema luego escribe el código.",
		"La perseverancia es la madre del éxito.",
	],
	german: [
		"Der einzige Weg großartige Arbeit zu leisten ist zu lieben was man tut.",
		"In der Mitte jeder Schwierigkeit liegt eine Möglichkeit.",
		"Es spielt keine Rolle wie langsam du gehst solange du nicht aufhörst.",
		"Die Zukunft hängt davon ab was du heute tust.",
		"Das Leben ist das was passiert während du damit beschäftigt bist andere Pläne zu machen.",
		"Glaub dass du es kannst und du bist schon auf halbem Weg.",
		"Glück ist nicht etwas Vorgefertigtes es kommt aus deinen eigenen Handlungen.",
		"Tu was du kannst mit dem was du hast wo du bist.",
		"Scheitern ist einfach die Möglichkeit neu anzufangen diesmal intelligenter.",
		"Der beste Zeitpunkt einen Baum zu pflanzen war vor zwanzig Jahren der zweitbeste Zeitpunkt ist jetzt.",
		"Erfolg ist kein Endpunkt Scheitern ist nicht tödlich es ist der Mut weiterzumachen der zählt.",
		"Phantasie ist wichtiger als Wissen.",
		"Wer kämpft kann verlieren wer nicht kämpft hat schon verloren.",
		"Der Mensch wächst mit seinen Aufgaben.",
		"Durch Fehler wird man klug.",
	],
	french: [
		"La seule façon de faire du bon travail est d'aimer ce que vous faites.",
		"Au milieu de chaque difficulté se trouve une opportunité.",
		"Peu importe la lenteur à laquelle vous allez tant que vous ne vous arrêtez pas.",
		"L'avenir dépend de ce que vous faites aujourd'hui.",
		"La vie est ce qui se passe pendant que vous êtes occupé à faire d'autres plans.",
		"Croyez que vous pouvez et vous êtes déjà à mi-chemin.",
		"Le bonheur n'est pas quelque chose de tout fait il vient de vos propres actions.",
		"Faites ce que vous pouvez avec ce que vous avez là où vous êtes.",
		"L'échec est simplement l'opportunité de recommencer cette fois plus intelligemment.",
		"Le meilleur moment pour planter un arbre était il y a vingt ans le deuxième meilleur moment c'est maintenant.",
		"Le succès n'est pas final l'échec n'est pas fatal c'est le courage de continuer qui compte.",
		"L'imagination est plus importante que la connaissance.",
		"La créativité c'est l'intelligence qui s'amuse.",
		"Celui qui déplace des montagnes commence par enlever de petites pierres.",
		"Mieux vaut tard que jamais.",
	],
};

export default quotes;
