export type LetterStatus = "correct" | "incorrect" | "idle" | "extra";

export type Mode = "words" | "time" | "quote";

export type TypingSettings = {
	mode: Mode;
	isPunctuation: boolean;
	isNumbers: boolean;
	count: number;
	language: string;
};

export type CursorPosition = {
	top: number;
	left: number;
};

export type Theme =
	| "pitch-black"
	| "hacker"
	| "matrix"
	| "midnight"
	| "obsidian"
	| "netflix"
	| "amber"
	| "neon"
	| "carbon"
	| "github"
	| "tokyo-night"
	| "midnight-blue"
	| "cyberpunk"
	| "vaporwave"
	| "rose-pine"
	| "catppuccin"
	| "kanagawa"
	| "dracula"
	| "one-dark"
	| "discord"
	| "gruvbox"
	| "dos"
	| "c64"
	| "ocean-deep"
	| "twitter"
	| "spotify"
	| "forest-night"
	| "everforest"
	| "volcano"
	| "halloween"
	| "coca-cola"
	| "mcdonalds"
	| "copper"
	| "gold"
	| "sunset"
	| "desert"
	| "cherry-blossom"
	| "coral"
	| "bubblegum"
	| "nord"
	| "solarized"
	| "gameboy"
	| "muted-grape"
	| "steel-blue"
	| "slate-mist"
	| "dusk"
	| "warm-gray"
	| "sandstone"
	| "dusty-rose"
	| "olive"
	| "mocha"
	| "slate"
	| "sage"
	| "sky"
	| "ocean-light"
	| "forest-light"
	| "peach"
	| "rose"
	| "lilac"
	| "butter"
	| "sage-light"
	| "arctic"
	| "lavender"
	| "mint"
	| "cream"
	| "paper"
	| "blush"
	| "lemon"
	| "cloud"
	| "snow"
	| "christmas"
	| "high-contrast"
	| "retro-terminal"
	| "synthwave"
	| "outrun"
	| "tron"
	| "lava"
	| "toxic"
	| "glacier"
	| "solar-flare"
	| "deep-purple"
	| "newspaper"
	| "blueprint"
	| "polaroid"
	| "8bit"
	| "wheat"
	| "ice"
	| "blood-moon"
	| "parchment";
